name = input("Enter your full name: ")
phone_number = input("Enter your phone number: ")
dashcounter = phone_number.count("-")
fixedphone = phone_number.replace("-", "")
result = len(name)
result2 = name.find("l")
result3 = name.rfind("l")
caps = name.capitalize()
upper = name.upper()
lower = name.lower()
digits = name.isdigit()
alpha = name.isalpha()
print(name)
print(f"Length is {result}")
print(f"Find result is {result2}")
print(f"RFind result is {result3}")
print(f"Result of caps is {caps}")
print(f"Result of upper is {upper}")
print(f"Result of lower is {lower}")
print(f"Result of digits is {digits}")
print(f"Result of alpha is {alpha}")
print(f"Result of phone dash counter is {dashcounter}")
print(f"The fixed phone number is is {fixedphone}")